spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      routes:

        # Account Service Routes
        - id: account-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/accounts/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20

        # Transaction Service Routes
        - id: transaction-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/transactions/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20

        # Payment Service Routes
        - id: payment-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
